experiment_id: "wva-sgd-1x-grads"
lambdas: [20500, 25250, 250]
net_struct: [784, 300, 150, 10]
learning_rate: 0.2
batch_size: 100
epoch_num: 4
repeats: 2
device: "cuda:4"
model_class: fc_sgd_wvaF_1x_grads.Model
validation_samples: 5000
importances_on_validation_samples: true
empirical_fisher: true